apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-front
  namespace: pbs-taiga
  labels:
    app: taiga-front
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: taiga-front
  template:
    metadata:
      labels:
        app: taiga-front
    spec:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      containers:
        - name: taiga-front
          image: ghcr.io/scout-ch/pbs-taiga-front:latest@sha256:af971a1903871cf203a3118b36560abc7e9a2c737ec761edd3a644852d4485af
          ports:
            - containerPort: 80
          env:
            - name: TAIGA_URL
              value: "https://taiga.scout.ch"
            - name: TAIGA_WEBSOCKETS_URL
              value: "wss://taiga.scout.ch"
            - name: TAIGA_SUBPATH
              value: ""
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 1
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-front
  namespace: pbs-taiga
spec:
  selector:
    app: taiga-front
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taiga-front
  namespace: pbs-taiga
  labels:
    app: taiga-front
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: taiga.scout.ch
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: taiga-front
                port:
                  number: 80
  tls:
    - hosts:
        - taiga.scout.ch
      secretName: tls-cert
