apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-async-rabbitmq
  namespace: pbs-taiga
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: taiga-async-rabbitmq
  namespace: pbs-taiga
spec:
  selector:
    matchLabels:
      app: taiga-async-rabbitmq
  serviceName: taiga-async-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: taiga-async-rabbitmq
    spec:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      containers:
        - name: taiga-async-rabbitmq
          image: rabbitmq:4.2-management-alpine@sha256:9651ce95332b3774065981d2a65e26edf259dd7a1bea387712e73095a1cec185
          ports:
            - containerPort: 5672
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            initialDelaySeconds: 60
            # See https://www.rabbitmq.com/monitoring.html for monitoring frequency recommendations.
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: taiga-mappable-secrets
                  key: ASNYC_RABBITMQ_ERLANG_COOKIE
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: taiga-mappable-config
                  key: ASYNC_RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: taiga-mappable-secrets
                  key: ASYNC_RABBITMQ_PASS
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                configMapKeyRef:
                  name: taiga-mappable-config
                  key: ASYNC_RABBITMQ_VHOST
            - name: X_RABBITMQ_VM_MEMORY_HIGH_WATERMARK
              value: "256MB"
          volumeMounts:
            - name: taiga-async-rabbitmq
              mountPath: /var/lib/rabbitmq/mnesia
            - name: memory-limit-config
              mountPath: /etc/rabbitmq/conf.d/20-memory-limit.conf
              subPath: 20-memory-limit.conf
      volumes:
        - name: taiga-async-rabbitmq
          persistentVolumeClaim:
            claimName: taiga-async-rabbitmq
        - name: memory-limit-config
          configMap:
            name: rabbitmq-memory-limit-config
            items:
              - key: 20-memory-limit.conf
                path: 20-memory-limit.conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-async
  namespace: pbs-taiga
  labels:
    app: taiga-async
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: taiga-async
  template:
    metadata:
      labels:
        app: taiga-async
    spec:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      affinity:
        podAffinity: # We need to schedule this on the same node as taiga-back because of shared volumes
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - taiga-back
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: taiga-static
          persistentVolumeClaim:
            claimName: taiga-static
        - name: taiga-media
          persistentVolumeClaim:
            claimName: taiga-media
      containers:
        - name: taiga-async
          image: ghcr.io/scout-ch/pbs-taiga-back:latest@sha256:ba89b4b703af3ab63d14669e790cf81e0bb4170ac1f92d2fd848e59087f02d29
          ports:
            - containerPort: 8000
          command: ["/taiga-back/docker/custom_entrypoint.sh"]
          args:
            [
              "celery",
              "-A",
              "taiga.celery",
              "worker",
              "-B",
              "--concurrency",
              "4",
              "-l",
              "INFO",
            ]
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: taiga-config
            - secretRef:
                name: taiga-secrets
          volumeMounts:
            - name: taiga-static
              mountPath: /taiga-async/static
            - name: taiga-media
              mountPath: /taiga-async/media
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-async-rabbitmq
  namespace: pbs-taiga
spec:
  selector:
    app: taiga-async-rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
